In [ ]:
import numpy as np #numerical Python
import pandas as pd #data analysis library

In [ ]:
df = pd.read_csv('diabetes.csv') #create a dataframe

In [ ]:
df.columns #Check for columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [ ]:
df.dtypes #check for data format

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness               float64
Insulin                     float64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [ ]:
df.head() #generate first 5 rows

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35.0,NaN,33.6,0.627,50,1
1,1,85,66,29.0,NaN,26.6,0.351,31,0
2,8,183,64,NaN,NaN,23.3,0.672,32,1
3,1,89,66,23.0,94.0,28.1,0.167,21,0
4,0,137,40,35.0,168.0,43.1,2.288,33,1

In [ ]:
len(df) #generate the number of observations

768

In [ ]:
df.shape #check for number of rows and columns (rows, columns)

(768, 9)

In [ ]:
df.isna().sum() #check for missing values

Pregnancies                   0
Glucose                       0
BloodPressure                 0
SkinThickness               227
Insulin                     374
BMI                           0
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

In [ ]:
df['SkinThickness'].fillna(df['SkinThickness'].mean(), inplace=True) #replace missing values with mean

<ipython-input-18-2556feea0ffb>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['SkinThickness'].fillna(df['SkinThickness'].mean(), inplace=True)

In [ ]:

df['SkinThickness'].mean()

29.15341959334565

In [ ]:
df.isna().sum()

Pregnancies                   0
Glucose                       0
BloodPressure                 0
SkinThickness                 0
Insulin                     374
BMI                           0
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

In [ ]:
df.head(50)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35.00000,NaN,33.6,0.627,50,1
1,1,85,66,29.00000,NaN,26.6,0.351,31,0
2,8,183,64,29.15342,NaN,23.3,0.672,32,1
3,1,89,66,23.00000,94.0,28.1,0.167,21,0
4,0,137,40,35.00000,168.0,43.1,2.288,33,1
5,5,116,74,29.15342,NaN,25.6,0.201,30,0
6,3,78,50,32.00000,88.0,31.0,0.248,26,1
7,10,115,0,29.15342,NaN,35.3,0.134,29,0
8,2,197,70,45.00000,543.0,30.5,0.158,53,1
9,8,125,96,29.15342,NaN,0.0,0.232,54,1
10,4,110,92,29.15342,NaN,37.6,0.191,30,0
11,10,168,74,29.15342,NaN,38.0,0.537,34,1
12,10,139,80,29.15342,NaN,27.1,1.441,57,0
13,1,189,60,23.00000,846.0,30.1,0.398,59,1
14,5,166,72,19.00000,175.0,25.8,0.587,51,1
15,7,100,0,29.15342,NaN,30.0,0.484,32,1
16,0,118,84,47.00000,230.0,45.8,0.551,31,1
17,7,107,74,29.15342,NaN,29.6,0.254,31,1
18,1,103,30,38.00000,83.0,43.3,0.183,33,0
19,1,115,70,30.00000,96.0,34.6,0.529,32,1
20,3,126,88,41.00000,235.0,39.3,0.704,27,0
21,8,99,84,29.15342,NaN,35.4,0.388,50,0
22,7,196,90,29.15342,NaN,39.8,0.451,41,1
23,9,119,80,35.00000,NaN,29.0,0.263,29,1
24,11,143,94,33.00000,146.0,36.6,0.254,51,1
25,10,125,70,26.00000,115.0,31.1,0.205,41,1
26,7,147,76,29.15342,NaN,39.4,0.257,43,1
27,1,97,66,15.00000,140.0,23.2,0.487,22,0
28,13,145,82,19.00000,110.0,22.2,0.245,57,0
29,5,117,92,29.15342,NaN,34.1,0.337,38,0
30,5,109,75,26.00000,NaN,36.0,0.546,60,0
31,3,158,76,36.00000,245.0,31.6,0.851,28,1
32,3,88,58,11.00000,54.0,24.8,0.267,22,0
33,6,92,92,29.15342,NaN,19.9,0.188,28,0
34,10,122,78,31.00000,NaN,27.6,0.512,45,0
35,4,103,60,33.00000,192.0,24.0,0.966,33,0
36,11,138,76,29.15342,NaN,33.2,0.420,35,0
37,9,102,76,37.00000,NaN,32.9,0.665,46,1
38,2,90,68,42.00000,NaN,38.2,0.503,27,1
39,4,111,72,47.00000,207.0,37.1,1.390,56,1
40,3,180,64,25.00000,70.0,34.0,0.271,26,0
41,7,133,84,29.15342,NaN,40.2,0.696,37,0
42,7,106,92,18.00000,NaN,22.7,0.235,48,0
43,9,171,110,24.00000,240.0,45.4,0.721,54,1
44,7,159,64,29.15342,NaN,27.4,0.294,40,0
45,0,180,66,39.00000,NaN,42.0,1.893,25,1
46,1,146,56,29.15342,NaN,29.7,0.564,29,0
47,2,71,70,27.00000,NaN,28.0,0.586,22,0
48,7,103,66,32.00000,NaN,39.1,0.344,31,1
49,7,105,0,29.15342,NaN,0.0,0.305,24,0

In [ ]:
df['Insulin'].fillna(df['Insulin'].mean(), inplace=True)

<ipython-input-25-004e9a71d0d1>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Insulin'].fillna(df['Insulin'].mean(), inplace=True)

In [ ]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
df.head(20)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35.00000,155.548223,33.6,0.627,50,1
1,1,85,66,29.00000,155.548223,26.6,0.351,31,0
2,8,183,64,29.15342,155.548223,23.3,0.672,32,1
3,1,89,66,23.00000,94.000000,28.1,0.167,21,0
4,0,137,40,35.00000,168.000000,43.1,2.288,33,1
5,5,116,74,29.15342,155.548223,25.6,0.201,30,0
6,3,78,50,32.00000,88.000000,31.0,0.248,26,1
7,10,115,0,29.15342,155.548223,35.3,0.134,29,0
8,2,197,70,45.00000,543.000000,30.5,0.158,53,1
9,8,125,96,29.15342,155.548223,0.0,0.232,54,1
10,4,110,92,29.15342,155.548223,37.6,0.191,30,0
11,10,168,74,29.15342,155.548223,38.0,0.537,34,1
12,10,139,80,29.15342,155.548223,27.1,1.441,57,0
13,1,189,60,23.00000,846.000000,30.1,0.398,59,1
14,5,166,72,19.00000,175.000000,25.8,0.587,51,1
15,7,100,0,29.15342,155.548223,30.0,0.484,32,1
16,0,118,84,47.00000,230.000000,45.8,0.551,31,1
17,7,107,74,29.15342,155.548223,29.6,0.254,31,1
18,1,103,30,38.00000,83.000000,43.3,0.183,33,0
19,1,115,70,30.00000,96.000000,34.6,0.529,32,1

In [ ]:
classification = {1: 'With Diabetes', 0: 'Without Diabetes'} #create a new column classifying the Outcome columns
df['Diagnosis'] = df['Outcome'].map(classification)

In [ ]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Diagnosis
0,6,148,72,35.00000,155.548223,33.6,0.627,50,1,With Diabetes
1,1,85,66,29.00000,155.548223,26.6,0.351,31,0,Without Diabetes
2,8,183,64,29.15342,155.548223,23.3,0.672,32,1,With Diabetes
3,1,89,66,23.00000,94.000000,28.1,0.167,21,0,Without Diabetes
4,0,137,40,35.00000,168.000000,43.1,2.288,33,1,With Diabetes

In [ ]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,29.153420,155.548223,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,8.790942,85.021108,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,7.000000,14.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,25.000000,121.500000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,29.153420,155.548223,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,155.548223,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000